<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>StopWatchTest</RootNamespace>
    <AssemblyName>StopWatchTest</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="RestSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StopWatch\StopWatch.csproj" />
  </ItemGroup>

</Project>
